export const listCards = [
  {
    id: 1,
    alt: 'Kitnet',
    src: 'https://via.placeholder.com/600x400',
    text: 'O quarto é muito bom, tem uma cama, um guarda roupa e uma mesa de estudos e um banheiro com chuveiro e pia  e um vaso sanitário. A cozinha é equipada com geladeira, fogão e microondas. A sala tem um sofá e uma televisão.',
    price: '500,00',
    services: ['Restaurante', 'Piscina', 'Wi-Fi'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 2,
    alt: 'Kitnet',
    src: 'https://via.placeholder.com/600x400',
    text: 'O quarto é muito bom, tem uma cama, um guarda roupa e uma mesa de estudos e um banheiro com chuveiro e pia  e um vaso sanitário. A cozinha é equipada com geladeira, fogão e microondas. A sala tem um sofá e uma televisão.',
    price: '500,00',
    services: ['Restaurante', 'Piscina', 'Wi-Fi'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 3,
    alt: 'Apartamento em frente à praia',
    src: 'https://via.placeholder.com/600x400',
    text: 'Apartamento espaçoso com vista para o mar, totalmente mobiliado e equipado com todas as comodidades necessárias para uma estadia confortável.',
    price: '1000,00',
    services: ['Piscina', 'Academia', 'Estacionamento'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 4,
    alt: 'Casa de campo aconchegante',
    src: 'https://via.placeholder.com/600x400',
    text: 'Casa de campo isolada com um belo jardim, perfeita para relaxar e desfrutar da natureza. Totalmente equipada com lareira e churrasqueira.',
    price: '800,00',
    services: ['Jardim', 'Churrasqueira', 'Lareira'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 5,
    alt: 'Loft moderno no centro da cidade',
    src: 'https://via.placeholder.com/600x400',
    text: 'Loft espaçoso e elegante localizado no coração da cidade, com fácil acesso a todas as principais atrações e comodidades urbanas.',
    price: '1200,00',
    services: ['Wi-Fi', 'Ar Condicionado', 'Cozinha Equipada'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 6,
    alt: 'Casa de praia luxuosa',
    src: 'https://via.placeholder.com/600x400',
    text: 'Mansão à beira-mar com piscina privativa, deck de madeira e vista panorâmica para o oceano. Acomodações de luxo para uma experiência inesquecível.',
    price: '2000,00',
    services: ['Piscina Privativa', 'Deck de Madeira', 'Vista para o Mar'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
  {
    id: 7,
    alt: 'Chalé nas montanhas',
    src: 'https://via.placeholder.com/600x400',
    text: 'Chalé rústico e acolhedor situado nas montanhas, cercado por paisagens deslumbrantes e trilhas naturais. Ideal para os amantes da natureza e da aventura.',
    price: '900,00',
    services: ['Trilhas Naturais', 'Vista Panorâmica', 'Lareira'],
    photos: [
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
      'https://via.placeholder.com/600x400',
    ],
    videos: [
      'https://www.youtube.com/embed/video1',
      'https://www.youtube.com/embed/video2',
    ],
  },
];
